# Kubernetes manifest file used to define and create a Kubernetes Secret resource

apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  username: bXl1c2Vy  # base64-encoded "myuser"
  password: bXlwYXNzd29yZA==  # base64-encoded "mypassword"

