# allows running pipelines and not full user access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-user-namespace
  name: test-user-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list"]
